/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bridge_Screenshot__ */

#ifndef _Included_bridge_Screenshot__
#define _Included_bridge_Screenshot__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bridge_Screenshot__
 * Method:    forApp
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bridge_Screenshot_00024_forApp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
